export type City = {
  slug:string; name:string; region:string; intro:string; local:string; projectTypes:string[];
};
export const CITIES:City[]=[
{slug:'vancouver',name:'Vancouver',region:'BC',intro:'Commercial wall and ceiling construction for Vancouver tenant improvements, offices, retail, restaurants, condos and custom interiors.',local:'Vancouver projects often combine tight access, occupied buildings, high-rise logistics and detailed coordination between framing, ceilings, mechanical, electrical and fire-protection trades.',projectTypes:['Tenant improvements','High-rise condo renovations','Retail and restaurants','Offices and commercial interiors']},
{slug:'burnaby',name:'Burnaby',region:'BC',intro:'Drywall, steel stud framing and suspended ceiling installation for commercial and residential projects across Burnaby.',local:'Burnaby has a broad mix of high-rise development, established commercial areas, institutional work and active tenant-improvement construction around major town centres.',projectTypes:['Commercial interiors','High-rise residential','Retail fit-outs','Office renovations']},
{slug:'surrey',name:'Surrey',region:'BC',intro:'Wall and ceiling contracting for Surrey commercial spaces, offices, warehouses, retail projects and residential construction.',local:'Surrey’s rapid growth creates demand across new commercial buildings, industrial spaces, tenant improvements and multi-family construction.',projectTypes:['Warehouses and industrial','Tenant improvements','Multi-family','Retail and offices']},
{slug:'richmond',name:'Richmond',region:'BC',intro:'Commercial drywall, steel stud and suspended ceiling work for Richmond offices, retail, restaurants and industrial interiors.',local:'Richmond projects frequently include commercial and industrial fit-outs, hospitality, retail and office spaces where ceiling-service coordination is critical.',projectTypes:['Commercial fit-outs','Industrial interiors','Restaurants and retail','Office renovations']},
{slug:'coquitlam',name:'Coquitlam',region:'BC',intro:'Steel stud framing, drywall and acoustic ceiling installation for Coquitlam commercial and residential interiors.',local:'Coquitlam combines growing high-density centres with retail, office, institutional and residential construction throughout the Tri-Cities.',projectTypes:['Tenant improvements','Multi-family','Retail','Commercial interiors']},
{slug:'port-coquitlam',name:'Port Coquitlam',region:'BC',intro:'Wall and ceiling construction for Port Coquitlam commercial, industrial and residential projects.',local:'Port Coquitlam’s mix of industrial areas, commercial spaces and residential growth creates varied framing, drywall and ceiling requirements.',projectTypes:['Industrial','Commercial renovations','Retail','Residential interiors']},
{slug:'port-moody',name:'Port Moody',region:'BC',intro:'Drywall, steel stud and ceiling contracting for Port Moody commercial and residential interiors.',local:'Port Moody combines dense residential development with neighbourhood retail, hospitality and commercial renovation work.',projectTypes:['Multi-family','Retail','Hospitality','Commercial interiors']},
{slug:'new-westminster',name:'New Westminster',region:'BC',intro:'Wall and ceiling installation for New Westminster condos, commercial interiors and renovation projects.',local:'New Westminster includes older building stock, high-rise residential, compact commercial spaces and renovation work that often requires careful field coordination.',projectTypes:['Condo renovations','Tenant improvements','Retail','Commercial interiors']},
{slug:'north-vancouver',name:'North Vancouver',region:'BC',intro:'Drywall, steel stud framing and suspended ceiling contracting across North Vancouver.',local:'North Vancouver work ranges from commercial and institutional interiors to custom residential and multi-family renovation projects.',projectTypes:['Commercial interiors','Custom homes','Multi-family','Retail']},
{slug:'west-vancouver',name:'West Vancouver',region:'BC',intro:'High-quality drywall, framing and ceiling work for West Vancouver custom residential and commercial interiors.',local:'West Vancouver projects often demand careful finish quality, custom detailing and coordination in premium residential and commercial environments.',projectTypes:['Custom homes','Renovations','Commercial interiors','Specialty ceilings']},
{slug:'delta',name:'Delta',region:'BC',intro:'Commercial wall, ceiling and steel stud contracting for Delta and surrounding industrial and residential areas.',local:'Delta includes major industrial and warehouse districts alongside retail, office and residential construction.',projectTypes:['Industrial','Warehouses','Commercial interiors','Residential']},
{slug:'langley',name:'Langley',region:'BC',intro:'Drywall, steel stud and suspended ceiling installation for Langley commercial, industrial and residential projects.',local:'Langley’s continued growth spans industrial buildings, retail, offices, multi-family and new commercial construction.',projectTypes:['Industrial','Retail','Multi-family','Commercial construction']},
{slug:'maple-ridge',name:'Maple Ridge',region:'BC',intro:'Wall and ceiling construction for Maple Ridge commercial spaces, residential projects and tenant improvements.',local:'Maple Ridge continues to add residential density and commercial services, creating a mix of renovation and new interior construction.',projectTypes:['Residential','Retail','Tenant improvements','Commercial interiors']},
{slug:'pitt-meadows',name:'Pitt Meadows',region:'BC',intro:'Drywall, steel stud framing and ceiling installation for Pitt Meadows commercial and residential projects.',local:'Pitt Meadows work includes industrial, commercial and residential interiors serving the growing northeast Metro Vancouver market.',projectTypes:['Industrial','Commercial','Residential','Tenant improvements']},
{slug:'white-rock',name:'White Rock',region:'BC',intro:'Wall and ceiling contracting for White Rock renovations, commercial interiors and residential projects.',local:'White Rock combines established residential properties, multi-family buildings and active hospitality and retail spaces.',projectTypes:['Renovations','Multi-family','Hospitality','Retail']},
{slug:'abbotsford',name:'Abbotsford',region:'BC',intro:'Commercial drywall, steel stud framing and suspended ceiling installation across Abbotsford.',local:'Abbotsford supports a large mix of industrial, institutional, retail, office and residential construction in the Fraser Valley.',projectTypes:['Industrial','Institutional','Retail','Commercial interiors']},
];
export const getCity=(slug:string)=>CITIES.find(c=>c.slug===slug);
